### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by urs-santoshh** [Omdena-NIC-Nepal/machine-learning-linear-regression-ai-dreamers#10]
#### **Description:**

We need to perform feature engineering to create new features that could potentially improve the model's performance. This includes testing different feature combinations and evaluating the impact of these new features on the model's performance. The work should be documented in the `notebooks/Feature_Engineering.ipynb` notebook.

#### **Tasks:**

1. **Create new features:**
   - Generate new features that might enhance the model's predictive capabilities.
   - Consider domain knowledge and data exploration findings to create meaningful features.

2. **Test different feature combinations:**
   - Experiment with various combinations of existing and newly created features.
   - Evaluate the impact of these combinations on the model's performance.

3. **Evaluate impact on model performance:**
   - Assess the performance of the model with the new features using relevant metrics.
   - Compare the results with the baseline model to determine the effectiveness of the new features.

4. **Document process and findings:**
   - Provide a detailed summary of the feature engineering process, including the rationale for creating new features and the impact of these features on model performance.
   - Include any relevant code snippets, plots, or metrics in the documentation.

#### **Assignment:**

Assign this issue to @rimalaayush . The assignee is responsible for completing the tasks outlined above and documenting their process in the `notebooks/Feature_Engineering.ipynb` notebook.

#### **Deadline:**

[Specify Deadline]

**Comment by rimalaayush** [comment]
Sure, I will work on this.
