### ISSUE TITLE
Task Distribution Discussion

### ISSUE THREAD

**Issue by urs-santoshh** [Omdena-NIC-Nepal/machine-learning-linear-regression-ai-dreamers#5]
#### Description:
To ensure efficient progress and clear responsibilities within our project, we need to discuss and distribute tasks among team members. This discussion will help us align on who will handle specific aspects of the project and ensure that all critical areas are covered.

#### Objectives:
- Assign each task to team members based on their expertise and interest.
- Establish deadlines and milestones for task completion.
- Ensure that all team members are aware of their responsibilities and deliverables.

#### Action Items:
1. Review the proposed tasks.
2. Suggest any additional tasks or modifications.
3. Assign tasks to team members.

Please provide your input and preferences regarding task distribution. Once we have a consensus, we can finalize the assignments and move forward with the project.

Thank you!

**Comment by sharad3595** [comment]
your suggestion is great. so lets everybody speak up which portion you actually think you are good at, don't necessarily have to be great. We will work together on doubts anyway.

**Comment by urs-santoshh** [comment]
yes i have created different issue according to tasks and lets divide each task to each other and will oversee the task and also keep the discussion related to the task in the respective issue thread

**Comment by urs-santoshh** [comment]
Issue no #7 has been assigned to @sharad3595

**Comment by urs-santoshh** [comment]
issue no #7 has been assigned to @Ashish-pixel333

**Comment by urs-santoshh** [comment]
issue no #11 has been assigned to @urs-santoshh

**Comment by urs-santoshh** [comment]
respective member will only work on the task issued and others will not make code changes directly in the file. The responsible member is the only one supposed to make changes in the specific task and file. But others can suggest the changes in the discussion int he specific issue thread

**Comment by urs-santoshh** [comment]
issue no #8 has been assigned to @BandanaAdhikar

**Comment by urs-santoshh** [comment]
issue no #10  has been assigned to @rimalaayush

**Comment by urs-santoshh** [comment]
i think all the task has been assigned to respective members. SO I am closing this issue. we will keep the discussion on the respective thread.
