### ISSUE TITLE
Model Training for Model_Training.ipynb

### ISSUE THREAD

**Issue by urs-santoshh** [Omdena-NIC-Nepal/machine-learning-linear-regression-ai-dreamers#8]
#### **Description:**

We need to perform model training for the dataset in the `notebooks/Model_Training.ipynb` notebook. This involves selecting appropriate features, training a linear regression model, and performing hyperparameter tuning if necessary. The corresponding script should be updated in `scripts/train_model.py`.

#### **Tasks:**

1. **Choose appropriate features:**
   - Select the most relevant features for the linear regression model based on previous data exploration and preprocessing steps.

2. **Train a linear regression model:**
   - Implement the linear regression model using the selected features.
   - Ensure the model is correctly trained and validated on the training data.

3. **Perform hyperparameter tuning (if applicable):**
   - Apply hyperparameter tuning techniques, such as grid search or random search, to optimize the model's performance.

4. **Update training script:**
   - Ensure that the model training steps are reflected in the `scripts/train_model.py` script for reproducibility.

5. **Document process and findings:**
   - Provide a summary of the model training steps, including the feature selection, training process, and any hyperparameter tuning performed.
   - Include performance metrics and any issues encountered.

#### **Assignment:**

Assign this issue to @BandanaAdhikar . The assignee is responsible for completing the tasks outlined above, updating the training script, and documenting their process in the `notebooks/Model_Training.ipynb` notebook.

#### **Deadline:**

[Specify Deadline]

**Comment by BandanaAdhikar** [comment]
**I will be working on thid issue..**
